Spring:
  application:
    name: SpringCloud-liugh-hello-zuul

server:
  port: 8089

zuul:
  routes:
    api_f_1:  #路径id  随意写
      path: /api_f/**   #映射路径
      url: http://localhost:8087  #映射路径对应的url地址


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
